# Remember that you must restart your web server if you want it to
# recognise changes made to this file while the server is running.

version: '2.7.0'

javascript_base_uri: '/yui'
additional_yui_javascripts:
  # - addition/addition  ...to load "base_url/version/build/addition/addition[-min].js"

xhr_timeout_ms: 30000

body_class: yui-skin-sam
div_class: yui-tree-container
div_id: yui-tree-container
target_form_field_id: yui-tree-form-field
